[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
#allowed_paths = ["/Users/udayvarma/UdayWorkSpace/Practice/Cyfrin-FoundryAdv.202505/02-NFTs-Collection/broadcast"]

remappings = ['@openzeppelin/contracts = lib/openzeppelin-contracts/contracts']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
